version: "3.7"
services:
  reverseproxy:
    build: ./reverseproxy
    container_name: reverseproxy
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"

  backend:
    build:
      context: ./backend
      args:
        - ENV=development
    container_name: backend
    command: npm start
    volumes:
      - ./backend/:/backend
      - ./secret/backend:/backend/secret
      - backend-modules:/backend/node_modules

  frontend:
    build:
      context: ./frontend
      args:
        - ENV=development
    container_name: frontend
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/frontend
      - ./secret/frontend:/frontend/src/secret
      - frontend-modules:/frontend/node_modules

volumes:
  backend-modules:
  frontend-modules:
