version: "3.7"
services: 
    backend:
        build: ./backend
        container_name: backend
        command: npm start
        ports:
            - "5000:5000"
    frontend:
        build: ./frontend
        container_name: frontend
        command: npm start
        ports:
            - "3000:3000"